### ISSUE TITLE
Deletes entire contents of .scss files

### ISSUE THREAD

**Issue by kyleramirez** [styled-components/stylelint-processor-styled-components#206]
I'm ditching this processor because it lost my trust and confidence, and it really isn't useful unless you get --fix to work. For those who see this in the future, this processor and the other `stylelint-config-styled-components` was developed so irresponsibly and narrow-mindedly that it will literally delete the contents your existing .scss files if you modify them. When used in combination with `lint-staged`, the entire contents of files you spent the last hour or so editing will be gone. All staged filed lost ... everything lost. Be better `stylelint-processor-styled-components`. What a ridiculous thing to mess up. I feel trolled.

**Comment by emilgoldsmith** [comment]
You know this is an open source project and people are contributing their spare time to improve it, right? Maybe you should've done the same instead of being so ungrateful. Also, read the documentation, we aren't hiding from the lack of `--fix` which is not supported by Stylelint (it's impossible for processors to support it)
