### ISSUE TITLE
Selector-class-pattern error everywhere since 1.0.2

### ISSUE THREAD

**Issue by monsieurnebo** [styled-components/stylelint-processor-styled-components#35]
After bumping from `v1.0.0` to `v1.0.2`, stylelint got mad and give us over 9000 errors like these:

```
 10:1  ✖  Expected class selector ".selector97" to match specified pattern    selector-class-pattern
 16:3  ✖  Expected class selector ".selector97" to match specified pattern    selector-class-pattern
 27:1  ✖  Unexpected empty line before rule                                   rule-empty-line-before
 27:1  ✖  Expected class selector ".selector98" to match specified pattern    selector-class-pattern
 31:1  ✖  Unexpected empty line before rule                                   rule-empty-line-before
 31:1  ✖  Expected class selector ".selector99" to match specified pattern    selector-class-pattern
 36:1  ✖  Unexpected empty line before rule                                   rule-empty-line-before
 36:1  ✖  Expected class selector ".selector100" to match specified pattern   selector-class-pattern
 44:1  ✖  Unexpected empty line before rule                                   rule-empty-line-before
 44:1  ✖  Expected class selector ".selector101" to match specified pattern   selector-class-pattern
 50:1  ✖  Unexpected empty line before rule                                   rule-empty-line-before
 50:1  ✖  Expected class selector ".selector102" to match specified pattern   selector-class-pattern
```

I didn't find any changelog --> have you any information about this?

**Comment by ismay** [comment]
I assume you mean 0.1.0 to 0.1.2. There have been a couple of changes, but I think what's affecting you is probably:

* https://github.com/styled-components/stylelint-processor-styled-components/commit/30a5f0ad1d7bc9b899a46582de1b7713a60f21d5
* https://github.com/styled-components/stylelint-processor-styled-components/commit/0f9e14615b7cc66319a47be25661c69e44b536f0

Of course, stylelint treats the way we're parsing the css as violations because of your rules. I don't know what you've set as your stylelint linting rules, but in any case you can just disable these specific ones because you have no control over the way we parse the css.

I'll create an issue for adding a changelog since we definitely need that. Also, currently we try to prevent situations like this by modifying the stylelint result after linting, but I think we'll move to a shareable stylelint config that you can extend in your stylelintrc. It'll override and enforce rules that are necessary for this processor to work.

Hope that answers your question, let me know if you have any other questions!

**Comment by monsieurnebo** [comment]
Thank's for the explanation, I fixed the concerned rules.

Changelog and extended config should definitly help :)

**Comment by ismay** [comment]
Great, happy it helped! Changelog is up btw.
